finished
casnerano/gophermart pull request #1
Opened 2023-02-20 09:12 UTC by casnerano

2023-02-21 20:26 UTC, ASPecherkin requested changes
Есть минорное замечание, которое быстро можно поправить

2023-02-21 20:26 UTC, ASPecherkin commented on build/nginx/conf.d/default.conf
> +upstream gophermart-upstream {
отлично , что и конфигруцию для nginx и полную обвязку для сервиса дописал

2023-02-21 20:26 UTC, ASPecherkin commented on cmd/gophermart/main.go
> +		panic(err)
не стоит паниковать даже в main 
лучше отписать что-то хотя бы в базовый лог 
и просто выйти

2023-02-21 20:26 UTC, ASPecherkin commented on cmd/gophermart/main.go
> +	userRepository := pgsql.NewUserRepository(connection)
вот примерно отсюда и ниже до 
```go
server := srv.New(config.Server.Address, router, logger)
```
лучше перенести в отдельную функцию здесь же , чтобы не перегружать main

2023-02-21 20:26 UTC, ASPecherkin commented on internal/repository/repository.go
> +type User interface {
отлично , что разделил на отдельные интерфейсы для каждой бизнес области

2023-02-21 20:40 UTC, ASPecherkin requested changes
Есть мелкое замечание, можно быстро его поправить

2023-02-21 21:10 UTC, casnerano commented on cmd/gophermart/main.go
> +		panic(err)
Поправил

2023-02-22 06:17 UTC, casnerano commented on cmd/gophermart/main.go
> +	userRepository := pgsql.NewUserRepository(connection)
А какое преимущество это даст, если останется так же в файле main.go ?
Кажется добавится чуть больше запутанности, т.к. получается появится какая-то функция которая будет одновременно инициализировать и возвращать роутер и запускать какие-то воркеры..

Честно говоря пока разобрался, в чем преимущество очень тонкого main.
Я так делал в предыдущем проекте - https://github.com/casnerano/go-url-shortener/blob/main/cmd/shortener/main.go

Мне кажется сейчас даже понятнее, что когда мы заходим в точку входа в приложение, мы сразу видим жизненный цикл инициализации основных точек приложения.

2023-02-22 06:18 UTC, casnerano commented on cmd/gophermart/main.go
> +	userRepository := pgsql.NewUserRepository(connection)
С другой стороны согласен, что можно было бы куда-то вынести инициализацию всяких репозиториев и сервисов, но в результате получится тоже самое.. Только дополнительный метод, который возвращает новую структуру с сервисами..

2023-02-26 18:47 UTC, ASPecherkin commented on cmd/gophermart/main.go
> +	userRepository := pgsql.NewUserRepository(connection)
тут скорее наследие C языков
где main , как и в Go - постоянная точка входа в программу и не более 
в Go это ещё место перехватывания сгналов, что логично для точки запуска 
И чаще всего этот код не сильно меняется 

Идея за тем, что я предложил - код в main в таком случае практически никогда не будет меняться, менять будет только дополнительная функция - помощник
если они станет слишком большая  - её части можно будет унести в другие пакеты по смыслу

2023-02-26 18:47 UTC, ASPecherkin commented on cmd/gophermart/main.go
> +	userRepository := pgsql.NewUserRepository(connection)
но тут я не настаиваю - общего правила, кроме как то, что не писать весь код в main в Go нет

2023-02-26 18:48 UTC, ASPecherkin approved these changes
Оставил некоторые моменты для будущих проектов, но ничего серьёзного , чтобы останавливало принятие работы тут нет

2023-02-26 19:00 UTC, merged